name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Log files in project root
        run: ls -R   # Recursively list all files in the project root directory

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Log files in the dist folder
        run: ls -R dist   # Recursively list all files in the dist directory

      - name: Upload macOS Artifacts
        if: success() && matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: |
            dist/*.dmg
            dist/*.zip

      - name: Upload Windows Artifacts
        if: success() && matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: win-build
          path: dist/*.exe
