name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload macOS Artifacts
        if: success() && matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: dist/*.dmg

      - name: Upload Windows Artifacts
        if: success() && matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: win-build
          path: dist/*.exe

      - name: Upload Linux Artifacts
        if: success() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: dist/*.AppImage
